from langchain_openai import OpenAIEmbeddings
from src.core.interfaces.embedding_service import EmbeddingService
from src.config.settings import settings
import logging
from typing import List, Optional
import asyncio

logger = logging.getLogger(__name__)


class OpenAIEmbeddingService(EmbeddingService):
    """OpenAI embedding service implementation"""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.api_key = api_key or settings.OPENAI_API_KEY
        self.model = model or settings.OPENAI_EMBEDDING_MODEL

        if not self.api_key:
            raise ValueError("OpenAI API key is required")

        # Initialize OpenAI client
        self.client = OpenAIEmbeddings(model=self.model, openai_api_key=self.api_key)

        logger.info(f"OpenAI Embedding Service initialized with model: {self.model}")

    async def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for multiple texts"""
        if not texts:
            return []

        try:
            # Validate texts
            valid_texts = self.validate_texts(texts)
            if not valid_texts:
                logger.warning("No valid texts provided for embedding generation")
                return []

            logger.info(
                f"Generating embeddings for {len(valid_texts)} texts using OpenAI"
            )

            # Generate embeddings
            embeddings = await self.client.aembed_documents(valid_texts)

            logger.info(f"Successfully generated {len(embeddings)} embeddings")
            return embeddings

        except Exception as e:
            logger.error(f"Failed to generate embeddings: {str(e)}")
            raise Exception(f"OpenAI embedding generation failed: {str(e)}")

    async def generate_single_embedding(self, text: str) -> List[float]:
        """Generate embedding for a single text"""
        if not self.validate_text(text):
            raise ValueError("Invalid text provided for embedding generation")

        try:
            logger.info("Generating single embedding using OpenAI")

            embedding = await self.client.aembed_query(text)

            logger.info("Successfully generated single embedding")
            return embedding

        except Exception as e:
            logger.error(f"Failed to generate single embedding: {str(e)}")
            raise Exception(f"OpenAI single embedding generation failed: {str(e)}")

    def get_embedding_dimension(self) -> int:
        """Get the dimension of embeddings generated by this service"""
        # OpenAI text-embedding-3-small generates 1536-dimensional vectors
        return 1536

    def is_available(self) -> bool:
        """Check if the service is available and configured"""
        return bool(self.api_key) and self.api_key != "your_openai_api_key_here"

    def get_service_name(self) -> str:
        """Get the name of the embedding service"""
        return "OpenAI"

    async def test_connection(self) -> bool:
        """Test the connection to OpenAI service"""
        try:
            test_text = "Test connection"
            embedding = await self.generate_single_embedding(test_text)

            if embedding and len(embedding) == self.get_embedding_dimension():
                logger.info("OpenAI connection test successful")
                return True
            else:
                logger.error("OpenAI connection test failed: invalid embedding format")
                return False

        except Exception as e:
            logger.error(f"OpenAI connection test failed: {str(e)}")
            return False

    def get_model_info(self) -> dict:
        """Get information about the current model"""
        return {
            "service": "OpenAI",
            "model": self.model,
            "dimension": self.get_embedding_dimension(),
            "api_key_configured": bool(self.api_key),
            "service_available": self.is_available(),
        }
