from abc import ABC, abstractmethod
from typing import List, Union, Optional
import numpy as np


class EmbeddingService(ABC):
    """Abstract interface for embedding generation services"""

    @abstractmethod
    async def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """Generate embeddings for a list of texts"""
        pass

    @abstractmethod
    async def generate_single_embedding(self, text: str) -> List[float]:
        """Generate embedding for a single text"""
        pass

    @abstractmethod
    def get_embedding_dimension(self) -> int:
        """Get the dimension of embeddings generated by this service"""
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """Check if the service is available and configured"""
        pass

    @abstractmethod
    def get_service_name(self) -> str:
        """Get the name of the embedding service"""
        pass

    def validate_text(self, text: str) -> bool:
        """Validate if text is suitable for embedding generation"""
        if not text or not text.strip():
            return False

        # Check if text is too long (most services have limits)
        if len(text) > 8000:  # OpenAI limit
            return False

        return True

    def validate_texts(self, texts: List[str]) -> List[str]:
        """Validate a list of texts and return valid ones"""
        valid_texts = []
        for text in texts:
            if self.validate_text(text):
                valid_texts.append(text)
        return valid_texts

    def batch_texts(
        self, texts: List[str], max_batch_size: int = 100
    ) -> List[List[str]]:
        """Split texts into batches for processing"""
        batches = []
        for i in range(0, len(texts), max_batch_size):
            batch = texts[i : i + max_batch_size]
            batches.append(batch)
        return batches

    async def generate_embeddings_batched(
        self, texts: List[str], max_batch_size: int = 100
    ) -> List[List[float]]:
        """Generate embeddings in batches to handle large text lists"""
        valid_texts = self.validate_texts(texts)

        if not valid_texts:
            return []

        batches = self.batch_texts(valid_texts, max_batch_size)
        all_embeddings = []

        for batch in batches:
            batch_embeddings = await self.generate_embeddings(batch)
            all_embeddings.extend(batch_embeddings)

        return all_embeddings
